### PR TITLE
Drop AKS `addon_profile`

### PR DESCRIPTION
**Pull request by heoelri**
See https://github.com/Azure/AlwaysOn-Foundational-Online/pull/149

### CODE REVIEW

**Comment by sebader** [comment]
does this require component-updates to be merged first?

**Comment by heoelri** [comment]
> does this require component-updates to be merged first?

preparing an e2e testrun

**Comment by heoelri** [comment]
https://dev.azure.com/alwayson/Foundational-Connected/_build/results?buildId=429&view=results

**Comment by heoelri** [comment]
Looks ok

image

**Comment by heoelri** [comment]
@sebader tested in e2e.

**Review by sebader — APPROVED** [review]

**Pull request merged**
